// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
 /* tslint:disable */
let _VERSION = '0.0.1-SNAPSHOT'; // This value will be overwritten by Webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by Webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
/* tslint:enable */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;
